---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
home: "appemit.com"
title: "Appemit"
keywords: "Embed App,游戏,办公,websocket,SSL,plugins,flash,mp4,flv,swf, m3u8,rtmp,mp3,aac"
description: "appemit.com，AppEmit是应用程序（尤其是浏览器）与本地程序间互相通信的易扩展的轻量级中间件"
source_link: "http://www.appemit.com"
favicon: "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
email: "appemit(at)appemit.com"
github: "https://github.com/appemit/appemit"
google_analytics_key:  UA-51913082-5 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

